pylibfdt: fix compatibility with python2
c001fc01a43e ("pylibfdt: fix swig build in install") introduced
python3-only super() invocation that fails with python2

  File "setup.py", line 48, in run
    return super().run()
TypeError: super() takes at least 1 argument (0 given)

while setup.py still claims to be compatible with both python versions:

>  While Python 3 is the default, it's also possible to invoke
>  this setup.py script with Python 2.

use legacy syntax that works in all python versions

Fixes: c001fc01a43e ("pylibfdt: fix swig build in install")
Signed-off-by: Jan Palus <jpalus@fastmail.com>